### ISSUE TITLE
Example should run without error

### ISSUE THREAD

**Issue by ofzeng** [SurrealAI/TorchX#5]
First, running this will generate the error "torch not defined".  Either import torch or use torchx.zeros().
Second, I get this mystery error below:
```root@gke-kurreal-1-nonagent-pool-gpu-80af7e7a-f22t:~# python3 script.py 
Traceback (most recent call last):
  File "script.py", line 18, in <module>
    model = MyModel()  # still on CPU
  File "/mylibs/torchx/torchx/torchx/utils/common.py", line 226, in __call__
    obj = super().__call__(*args, **kwargs)
  File "script.py", line 9, in __init__
    self.fc1 = nn.Linear(10, 20)
  File "/mylibs/miniconda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 558, in __setattr__
    "cannot assign module before Module.__init__() call")
AttributeError: cannot assign module before Module.__init__() call
```

```
import torchx as tx
import torch.nn as nn  # builtin
import torchx.nn as nnx

# use it the same way as nn.Module
class MyModel(nnx.Module):
    def __init__(self):
        self.fc1 = nn.Linear(10, 20)
        self.fc2 = nn.Linear(20, 30)
    
    def forward(self, x):
        return self.fc2(self.fc1(x))
        

with tx.device_scope(3):
    x = torch.zeros((4, 10))  # on GPU 3    ############TODO: torch not defined
    model = MyModel()  # still on CPU
    y = model(x)  # this call automatically transfers model to GPU 3
    print(y)  # shape (4, 30), on GPU 3```

**Comment by ofzeng** [comment]
I believe the model is missing a super().__init__() call

**Comment by LinxiFan** [comment]
you are right, the example script is sloppy. Good catch. I just added super().init

**Comment by ofzeng** [comment]
This example is still missing an `import torch`
